trigger:
- none

parameters:
  - name: workingDirectory
    type: string
    default: "$(Build.SourcesDirectory)/infra_basica"
  
  - name: Action
    displayName: Action
    type: string
    default: 'Apply'
    values:
    - Installer
    - Init
    - Plan
    - Apply
    - Destroy

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV2@2
  displayName: INIT
  inputs:
    workingDirectory: '${{ parameters.workingDirectory }}'
    provider: 'aws'
    command: 'init'
    backendServiceAWS: 'AWS_INFRA_BASICA'
    backendAWSBucketName: 'tis-automation-bucket'
    backendAWSKey: 'terraform.tfstate'

- task: TerraformTaskV2@2
  displayName: VALIDATE
  inputs:
    workingDirectory: '${{ parameters.workingDirectory }}'
    provider: 'aws'
    command: 'validate'

- task: TerraformTaskV2@2
  #condition: ne('${{ parameters.Action }}', 'Destroy')
  displayName: PLAN
  inputs:
    workingDirectory: '${{ parameters.workingDirectory }}'
    provider: 'aws'
    command: 'plan'
    environmentServiceNameAWS: 'AWS_INFRA_BASICA'

- task: TerraformTaskV2@2
  condition: ne('${{ parameters.Action }}', 'Destroy')
  displayName: APPLY
  inputs:
    provider: 'aws'
    command: 'apply'
    commandOptions: '-auto-approve'
    environmentServiceNameAWS: 'AWS_INFRA_BASICA'

- task: TerraformTaskV2@2
  condition: eq('${{ parameters.Action }}', 'Destroy')
  displayName: DESTROY
  inputs:
    provider: 'aws'
    command: 'destroy'
    commandOptions: '-auto-approve'
    environmentServiceNameAWS: 'AWS_INFRA_BASICA'