trigger:
- none

parameters:
  - name: workingDirectory
    type: string
    default: "$(Build.SourcesDirectory)/infra_basica"
  
  - name: Action
    displayName: Action
    type: string
    default: 'Apply'
    values:
    - Installer
    - Init
    - Plan
    - Apply
    - Destroy

pool:
  vmImage: ubuntu-latest

jobs:
  - job: terraform_installer
    condition: eq('${{ parameters.Action }}', 'Installer') and ne('${{ parameters.Action }}', 'Destroy')
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'

  - job: terraform_init
    condition: eq('${{ parameters.Action }}', 'Init') and ne('${{ parameters.Action }}', 'Destroy')
    steps:
    - task: TerraformTaskV2@2
      displayName: INIT
      inputs:
        provider: 'aws'
        command: 'init'
        workingDirectory: '${{ parameters.workingDirectory }}'
        backendServiceAWS: 'AWS_INFRA_BASICA'
        backendAWSBucketName: 'tis-automation-bucket'
        backendAWSKey: 'terraform.tfstate'
  
  - job: terraform_validate
    condition: eq('${{ parameters.Action }}', 'Validate') and ne('${{ parameters.Action }}', 'Destroy')
    steps:
    - task: TerraformTaskV2@2
      condition: ne('${{ parameters.Action }}', 'Destroy')
      displayName: VALIDATE
      inputs:
        workingDirectory: '${{ parameters.workingDirectory }}'
        provider: 'aws'
        command: 'validate'

  - job: terraform_plan
    condition: eq('${{ parameters.Action }}', 'Plan') and ne('${{ parameters.Action }}', 'Destroy')
    steps:
    - task: TerraformTaskV2@2
      condition: ne('${{ parameters.Action }}', 'Destroy')
      displayName: PLAN
      inputs:
        workingDirectory: '${{ parameters.workingDirectory }}'
        provider: 'aws'
        command: 'plan'
        environmentServiceNameAWS: 'AWS_INFRA_BASICA'