trigger:
- none

parameters:
  - name: workingDirectory
    type: string
    default: "$(Build.SourcesDirectory)/infra_basica"

  - name: Action
    displayName: Action
    type: string
    default: 'Apply'
    values:
    - Plan
    - Apply
    - Destroy

pool:
  vmImage: ubuntu-latest

stages:
- stage: terraform_install  # name of the stage, A-Z, a-z, 0-9, and underscore
  displayName: Terraform Install   # friendly name to display in the UI
  #dependsOn: string | [ string ]
  #condition: string
  #pool: string | pool
  #variables: { string: string } | [ variable | variableReference ] 
  jobs:
  - job: install
    steps:
    - script: |
        sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update && sudo apt-get install terraform
        terraform --version

- stage: terraform_init  # name of the stage, A-Z, a-z, 0-9, and underscore
  displayName: Terraform Init   # friendly name to display in the UI
  dependsOn: terraform_install
  condition: and(succeeded('terraform_install'), ne('${{ parameters.Action }}', 'Destroy'))
  #pool: string | pool
  #variables: { string: string } | [ variable | variableReference ] 
  jobs:
  - job: Init
    steps:
    - task: CmdLine@2
      inputs:
        workingDirectory: '${{ parameters.workingDirectory }}'
        script: |
          export AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID)
          export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
          terraform --version
          terraform init

- stage: terraform_plan  # name of the stage, A-Z, a-z, 0-9, and underscore
  displayName: Terraform Plan   # friendly name to display in the UI
  dependsOn: terraform_init
  condition: and(succeeded('terraform_init'), ne('${{ parameters.Action }}', 'Destroy'))
  #pool: string | pool
  #variables: { string: string } | [ variable | variableReference ] 
  jobs:
  - job: Plan
    steps:
    - task: CmdLine@2
      inputs:
        workingDirectory: '${{ parameters.workingDirectory }}'
        script: |
          export AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID)
          export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
          terraform --version
          terraform init
          terraform plan

- stage: terraform_apply  # name of the stage, A-Z, a-z, 0-9, and underscore
  displayName: Terraform Apply   # friendly name to display in the UI
  dependsOn: terraform_plan
  condition: and(succeeded('terraform_plan'), ne('${{ parameters.Action }}', 'Destroy'), eq('${{ parameters.Action }}', 'Apply'))
  #pool: string | pool
  #variables: { string: string } | [ variable | variableReference ] 
  jobs:
  - job: Apply
    steps:
    - task: CmdLine@2
      inputs:
        workingDirectory: '${{ parameters.workingDirectory }}'
        script: |
          export AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID)
          export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
          terraform --version
          terraform apply -auto-approve
#          terraform apply