trigger:
- none

parameters:
  - name: workingDirectory
    type: string
    default: "$(Build.SourcesDirectory)/infra_basica"
  
  - name: Action
    displayName: Action
    type: string
    default: 'Apply'
    values:
    - Plan
    - Apply
    - Destroy

pool:
  vmImage: ubuntu-latest

stages:
  - stage: terraform_installer
    - task: TerraformInstaller@0
      inputs:
   terraformVersion: 'latest'

  - stage: terraform_init
    - task: TerraformTaskV2@2
      displayName: INIT
      inputs:
        workingDirectory: '${{ parameters.workingDirectory }}'
        provider: 'aws'
        command: 'init'
        backendServiceAWS: 'AWS_INFRA_BASICA'
        backendAWSBucketName: 'tis-automation-bucket'
        backendAWSKey: 'terraform.tfstate'

  - stage: terraform_validate
    - task: TerraformTaskV2@2
      condition: ne('${{ parameters.Action }}', 'Destroy')
      displayName: VALIDATE
      inputs:
        workingDirectory: '${{ parameters.workingDirectory }}'
        provider: 'aws'
        command: 'validate'

  - stage: terraform_plan
    - task: TerraformTaskV2@2
      condition: ne('${{ parameters.Action }}', 'Destroy')
      displayName: PLAN
      inputs:
        workingDirectory: '${{ parameters.workingDirectory }}'
        provider: 'aws'
        command: 'plan'
        environmentServiceNameAWS: 'AWS_INFRA_BASICA'