trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV2@2
  inputs:
    provider: 'aws'
    command: 'init'
    backendServiceAWS: 'AWS_INFRA_BASICA'
    backendAWSBucketName: 'tis-automation-bucket'
    backendAWSKey: 'terraform.tfstate'

- task: TerraformTaskV2@2
  inputs:
    provider: 'aws'
    command: 'validate'

- task: TerraformTaskV2@2
  inputs:
    provider: 'aws'
    command: 'plan'
    environmentServiceNameAWS: 'AWS_INFRA_BASICA'