trigger:
- none

pool:
  vmImage: ubuntu-latest

stages:
- stage: terraform_install  # name of the stage, A-Z, a-z, 0-9, and underscore
  displayName: Terraform Install   # friendly name to display in the UI
  #dependsOn: string | [ string ]
  #condition: string
  #pool: string | pool
  #variables: { string: string } | [ variable | variableReference ] 
  jobs:
  - job: install
    steps:
    - script: |
        sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update && sudo apt-get install terraform
        terraform --version